"""
Django settings for evchat project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

redis_host = os.environ.get('REDIS_HOST', '127.0.0.1')

CHANNELS_LAYERS = {
    "default": {
        "BACKEND": "channel_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)]
        },
        # 'ROUTING': 'evchat.routing.channel_routing'
    }
}


ASGI_APPLICATION = "evchat.routing.application"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a%=evyn!b-kv&pe&6vg0l^y94q&5d9smfddw9&0t2h)**o^o-r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pymemcache',
    'bootstrap3',
    'channels',
    'rest_framework',
    'chat',
    'events',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'evchat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evchat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# LOGIN_REDIRECT_URL = "/index"
LOGIN_URL = "/auth"

MEDIA_ROOT = '/media/'
MEDIA_URL = '/media/'

# Rest-framework settings
REST_FRAMEWORK = {
    'DATETIME_FORMAT': "%m/%d/%Y %H:%M",
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGINATE_BY': 10
}

# Specific settings
IS_ENTER_OR_LEAVE_ROOMS = True

MESSAGE_TYPES_CHOICES = {
    0: 'MESSAGE',
    1: 'WARNING',
    2: 'ALERT',
    3: 'MUTED',
    4: 'ENTER',
    5: 'LEAVE'
}

TYPES_BY_MESSAGES = {
    'MESSAGE': 0,
    'WARNING': 1,
    'ALERT': 2,
    'MUTED': 3,
    'ENTER': 4,
    'LEAVE': 5
}
## Auth by phone settings
MIN_ACCEPT_CODE_VAL = 100001
MAX_ACCEPT_CODE_VAL = 999998

# Event Settings
DATETIME_FORMAT = "%d/%m/%Y %H:%M"
from django.conf.global_settings import DATETIME_INPUT_FORMATS

DATETIME_INPUT_FORMATS.append(DATETIME_FORMAT)